image: node:16

stages:
  - build
  - deploy

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - node_modules/

build:
  stage: build
  script:
    - npm ci
    - npm run build
  artifacts:
    paths:
      - build

pages:
  stage: deploy
  script:
    - cp -r build/* public/
  artifacts:
    paths:
      - public
